<main id="home" class="py-5 px-3">
    <h1 class="mb-5">Secured Blog</h1>

    <h2 class="mt-5">Latest posts</h2>
    <ul class="row mt-5">
        <?php if (!empty($data['posts'])): ?>
            <?php foreach ($data['posts'] as $post): ?>
                <li class="col-4 my-2">
                    <article class="card">
                        <header class="card-body">
                            <h3 class="h5 card-title"><?= htmlspecialchars($post->getTitle()) ?></h3>
                            <h4 class="h6 card-subtitle mb-2 text-body-secondary">
                                <?php foreach ($post->getCategories() as $cat): ?>
                                    <?php
                                        if (is_object($cat)) {
                                            echo htmlspecialchars($cat->getTitle());
                                        } elseif (is_array($cat) && isset($cat['title'])) {
                                            echo htmlspecialchars($cat['title']);
                                        } elseif (is_string($cat)) {
                                            echo htmlspecialchars($cat);
                                        }
                                    ?><br>
                                <?php endforeach; ?>
                            </h4>
                        </header>
                        <section class="card-body">
                            <p class="card-text"><?= htmlspecialchars($post->getExcerpt()) ?></p>
                            <a href="index.php?route=post&post_id=<?= $post->getId() ?>" class="btn btn-primary">Voir le post</a>
                        </section>
                        <footer class="card-footer text-muted">
                            Par <?= htmlspecialchars($post->getAuthor()->getUsername()) ?>, le <?= $post->getCreatedAt()->format('d/m/Y') ?>
                        </footer>
                    </article>
                </li>
            <?php endforeach; ?>
        <?php else: ?>
            <li>Aucun post à afficher.</li>
        <?php endif; ?>
    </ul>
</main>